name: smartrecycler
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.10+1
  retrofit: ^4.0.3
  build_runner: ^2.1.10
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.0.8
  logger: ^2.0.2+1
  async: ^2.3.0 #AsyncMemoizer 클래스

  flutter_secure_storage : ^9.0.0 #자동 로그인 관련
  
  # progress bar 사용하기 위한 dependency 추가
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.0.1
  animated_bottom_navigation_bar: ^1.3.0 # animate 바텀네비게이션 바 적용
  circular_reveal_animation: ^2.0.1
  anim_search_bar: ^2.0.3 # search bar
  transformable_list_view: ^0.4.0

  url_launcher: ^6.2.1 #하이퍼링크 관련

  image: ^4.1.3

  aws_s3_upload: ^1.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.3
  path_provider: ^2.1.0
  dio: ^5.3.3
  permission_handler: ^11.0.1

  image_picker: ^1.0.4
  gif: ^2.2.0

  flutter_vision: ^1.1.4
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^5.0.0+1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/splashImage.png
    - assets/images/profile.png

flutter_native_splash:
  image: assets/ic_launcher.png
  color: "#ffffff"
  fonts:
    - family: Pretendard
      fonts:
       - asset: fonts/Pretendard-Regular.ttf
         weight: 300
       - asset: fonts/Pretendard-SemiBold.ttf
         weight: 600

